Course 4 - First PR
IlyaKhalizov/golang-united-courses pull request #3
Opened 2022-11-08 10:19 UTC by Licheropew

2022-11-09 19:33 UTC, ivangurin requested changes

2022-11-09 19:33 UTC, ivangurin commented on config/config.go
> +func GetConfig() string {
Потенциально конфиг может возвращать не только строку соединения, но и другие параметры. Я бы сделал возврат структуры конфига с полями. Но в этом случае есть один минус. При вызове конфига несколько раз будут каждый раз перечитываться. Поэтому еще лучше сделать переменную структуры на уровне пакета и проверять ее на нил. Если она нил, то заполнят и возвращать. Если не нил, то сразу возращать. Либо эту переменную сделать публичной чтобы кому нужно к ней обращались.

Все значения переменных окружения я был добавил в конфиг.

2022-11-09 19:33 UTC, ivangurin commented on pkg/models/course.go
> +	gorm.Model
Соответственно от сюда убираем gorm.Model и добавляем Id c типом стринг.

2022-11-09 19:33 UTC, ivangurin commented on pkg/service/courses.go
> +		return nil, status.Error(codes.Internal, fmt.Sprintf("Can't create item. Reason: %s", t.Error))
Текст ошибки возвращаем абстрактный типа внутренняя ошибка и все такой. Реальный тип ошибки выводим в лог. Тот кто вызывает апи не должен знать из за чего реально ошибка.

2022-11-09 19:33 UTC, ivangurin commented on pkg/service/courses.go
> +	course.ID = uint(request.Id)
Тут будет генерация UUID

2022-11-09 19:33 UTC, ivangurin commented on pkg/service/courses.go
> +	t := s.Course.DB.Limit(int(request.Limit)).Offset(int(request.Offset)).Find(&courses, "user_id = ?", request.UserId)
А если лимит, оффсет и юзер не заданы, то данные выберутся?

2022-11-09 20:13 UTC, ivangurin commented
Запустил я у себя твой сервис. 
1. Метод Create работает.
2. Метод Get работает. 
3. Метод Update не работает.
4. Метод Delete работает. Но не обновилось поле deleted_by. И после удаления записи она не возвращается с помощью метода Get - выдает код ошибки NOT_FOUND.
5. Метод List ничего не возвращает какие либо параметры я не вводил. Даже если ничего не указывает, то тоже ничего не возвращает.

2022-11-09 20:54 UTC, koldyba commented on pkg/service/courses.go
> +	course.ID = uint(request.Id)
Это же гет, зачем тут генерация?

2022-11-10 07:37 UTC, Licheropew commented on pkg/service/courses.go
> +		DeletedAt:   timestamppb.New(course.DeletedAt.Time),
Да, замечал такое. Это исправлю, хотя думал что может есть какие-то инструменты у GORM, которые это сделают, но не нашёл пока ничего.

2022-11-10 07:39 UTC, Licheropew commented on pkg/service/courses.go
> +	t := s.Course.DB.Limit(int(request.Limit)).Offset(int(request.Offset)).Find(&courses, "user_id = ?", request.UserId)
По идее нет, т.к. эти параметры будут 0 (надо проверить, кстати). С другой стороны, если я правильно понимаю, эти параметры обязательны для заполнения или я неправильно понимаю.

2022-11-10 07:41 UTC, ivangurin commented on pkg/service/courses.go
> +	t := s.Course.DB.Limit(int(request.Limit)).Offset(int(request.Offset)).Find(&courses, "user_id = ?", request.UserId)
Они не обязательны.

2022-11-10 07:41 UTC, Licheropew commented on pkg/models/course.go
> +	gorm.Model
Тут вопрос, стоит ли убирать gorm.Model. Так как у него реализован soft delete из коробки, например, ну и соответственно поля deleted_at, updated_at, created_at.
С другой стороны, чтобы просматривать удаленные данные через soft delete, нужно указывать дополнительный параметр в запросе Unscoped.
А нужно ли выводить удаленные записи?
Потому пока сделал так, заодно проверить и потестировать.

2022-11-10 07:43 UTC, Licheropew commented on pkg/service/courses.go
> +	t := s.Course.DB.Limit(int(request.Limit)).Offset(int(request.Offset)).Find(&courses, "user_id = ?", request.UserId)
Тогда ок, добавлю проверку. Спасибо.

2022-11-10 07:45 UTC, ivangurin commented on pkg/models/course.go
> +	gorm.Model
Get точно должен отдавать запись. Для листа нужно в запросе сделать отдельные параметр при указании которого будут отдаваться и удаленные.

2022-11-10 07:46 UTC, Licheropew commented
С методом Update что-то сломалось, пока ищу в чем причина. До этого работал, пока что-то не поменял)
Метод Delete работает, а не возвращает из-за отсутствия параметра Unscoped в GET (soft delete в GORM так работает).
На счет List - перепроверю, аналогично Update.
Спасибо!

2022-11-10 07:47 UTC, ivangurin commented on pkg/service/courses.go
> +	course.ID = uint(request.Id)
> Это же гет, зачем тут генерация?

Тут нет генерации. Это специфика горма. У модели указать ее код и по этому коду он подтянет все данные из БД.

2022-11-10 07:51 UTC, ivangurin commented
Не используй у горма метод Delete. При его использовании он только обновит поле deleted_at и не обновит deleted_by.

2022-11-10 12:45 UTC, Licheropew commented on api/proto/courses.proto
> +    uint32 user_id = 4;
Исправил. Теперь ID курсов и юзеров - string.

2022-11-10 12:49 UTC, Licheropew commented on api/proto/courses.proto
> +    uint32 id = 1;
Fixed.

2022-11-10 12:52 UTC, Licheropew commented on pkg/service/courses.go
> +		DeletedAt:   timestamppb.New(course.DeletedAt.Time),
Добавил дополнительную проверку на время.

2022-11-10 12:52 UTC, Licheropew commented on pkg/service/courses.go
> +	t := s.Course.DB.Limit(int(request.Limit)).Offset(int(request.Offset)).Find(&courses, "user_id = ?", request.UserId)
Fixed.

2022-11-10 12:58 UTC, Licheropew commented
Update, Delete, List - снова работают как надо.
В первых двух была проблема с тем, что при поиске First я обновлял модель курсов (подтягивал данные из базы старые, перезаписывая новые из реквеста.
В List куда-то пропала модель курсов, поэтому он ничего не возвращал.
Спасибо! :)

На счет метода Delete у GORM, я его пока оставлю. Просто перед ним сработает Update (обновим deleted_by) -> Delete (автоматически подтянет время удаления). Не знаю насколько это правильно, и логичнее напрашивается просто один Update с обновлением ещё deleted_at.

2022-11-10 15:24 UTC, ivangurin commented
Проверил. Все работет.

2022-11-13 07:49 UTC, RealJimy requested changes

2022-11-13 07:49 UTC, RealJimy commented on api/proto/courses.proto
> +option go_package = "./pkg/api";
По структуре каталогов проекта подсмотри у Ивана и Сергея. Давайте придерживаться одного стиля.

2022-11-13 07:49 UTC, RealJimy commented on pkg/models/course.go
> +	UserID      string `gorm:"index"`
Связь студента (пользователя) и курса - многие ко многим. Один курс проходят много учеников, один ученик может проходить (параллельно или последовательно) несколько курсов.
Тут одной таблицей не обойтись.

2022-11-22 17:05 UTC, RealJimy commented on internal/repositories/courses/user_courses.go
> +	err := p.DB.Create(&uc).Error
Нужно подумать как обработать ситуацию с повторным Join. Например, я на странице курса нажал "Присоединиться" потом тупо передумал и нажал "Уйти с курса" а потом передумал еще раз и снова нажал "Присоединиться"

2022-11-22 17:05 UTC, RealJimy commented on api/proto/courses.proto
> +    uint32 persent_finished = 3;
perCent

2022-11-25 09:12 UTC, Licheropew commented on api/proto/courses.proto
> +message UserCourse {
Да, как-то упустил. Поменяю.

2022-11-25 09:15 UTC, Licheropew commented on cmd/main.go
> +	runApp()
В текущем варианте никакого. Возможно пригодится в будущем. Например, разделить на отдельные функции подключение к базе данных и создание gprc-сервера. Какие-то дополнительные возможности если будем реализовывать в виде горутин и т.д.
Если это неактуально, то могу все в main закинуть.

2022-11-25 10:40 UTC, Licheropew commented on config/config.go
> +var cfg *Config
Да, логично. Поменяю, сделаю сразу return.

2022-11-25 10:45 UTC, Licheropew commented on internal/api/courses.go
> +func checkIsValidUUID(id string) (uuid.UUID, error) {
Я изначально делал возврат bool значения, потому логика была соблюдена, но потом нашёл более удобный для меня путь. Потому реализацию функции я изменил, а вот название уже не менял :)

2022-11-25 10:46 UTC, Licheropew commented on internal/api/courses.go
> +	return cid, nil
Выше написал причину появления этой функции. Потому её и не убирал, а так да, сейчас вижу что можно её убрать. Поменяю.

2022-11-25 10:50 UTC, Licheropew commented on api/proto/courses.proto
> +    uint32 persent_finished = 3;
Понятия не имею как так вышло)) Спасибо за внимательность! Поменяю обязательно.

2022-11-25 11:25 UTC, Licheropew commented on internal/repositories/courses/user_courses.go
> +	err := p.DB.Create(&uc).Error
Подумаю. Пока вижу два пути:
1) Оставить db.Create, обработать ошибку "duplicate key..". Если она есть, тогда проверить статус (например, "deleted") и тогда через Update обновить его
2) Сделать проверку через GetUserCourse. Если возвращается ErrNotFound, просто создаем, если ошибок нет -> update.
3) Через ListUserCourse. Если len(list) == 0, создаем, иначе обновляем.

Пока второй кажется более оптимальным. Не нужно реализовывать проверку на новую ошибку.
Но ещё подумаю.

2022-11-29 08:13 UTC, RealJimy commented on cmd/main.go
> +	"golang-united-courses/internal/interfaces.go"
"**.go**" в имени каталога

2022-11-29 08:19 UTC, RealJimy commented on cmd/main.go
> +	dbUrl := fmt.Sprintf("host=%s user=%s password=%s dbname=%s port=%s sslmode=%s TimeZone=%s",
Эта строка параметров общая для любых СУБД или характерна только для Postrgre?

2022-11-29 08:37 UTC, RealJimy commented on cmd/main.go
> +	}
Можно сделать у api метод, например Init, который будет принимать в качестве параметра myDb, инстанцировать и возвращать структуру CourseServer. Типа конструктора в ООП. Тут останется что-то типа
```
myCourseServer := api.Init(myDb)
```
Принципиально ни на что не влияет, но код выглядит чище и main больше не должен знать о внутренней структуре полей CourseServer чтобы ее заполнить.

2022-11-29 08:39 UTC, RealJimy commented on cmd/main.go
> +	c, err := net.Listen("tcp", ":8080")
Порт лучше убрать в конфиг.

2022-11-29 08:41 UTC, RealJimy commented on cmd/main.go
> +	if err := s.Serve(c); err != nil {
Слишком много ничего не говорящих переменных. Страдает самодокументация кода

2022-11-29 08:51 UTC, RealJimy commented on cmd/main.go
> +	if err := godotenv.Load(); err != nil {
Может убрать это внутрь пакета config? Каких-то весомых аргументов не могу тут привести, просто main станет полегче.

2022-11-30 08:48 UTC, Licheropew commented on api/proto/courses.proto
> +    repeated GetResponse courses = 1;
Добавил.

2022-11-30 08:48 UTC, Licheropew commented on api/proto/courses.proto
> +    repeated UserCourseResponse user_courses = 1;
Добавил.

2022-11-30 08:49 UTC, Licheropew commented on cmd/main.go
> +	dbUrl := fmt.Sprintf("host=%s user=%s password=%s dbname=%s port=%s sslmode=%s TimeZone=%s",
Перенес в case с postgres.

2022-11-30 08:49 UTC, Licheropew commented on internal/models/course.go
> +type Database struct {
Убрал, добавлял её для каких-то целей, потом не удалил.

2022-11-30 08:49 UTC, Licheropew commented on config/config.go
> +			SslMode:  os.Getenv("COURSES_DB_TZ"),
Пофиксил.

2022-11-30 08:51 UTC, Licheropew commented on cmd/main.go
> +	"golang-united-courses/internal/interfaces.go"
Пофиксил.

2022-11-30 14:39 UTC, Licheropew commented on cmd/main.go
> +	}
Добавил функцию New с параметром интерфейса.

2022-12-02 06:55 UTC, Licheropew commented on cmd/main.go
> +	c, err := net.Listen("tcp", ":8080")
Добавил. Оставил переменную port на случай, если в конфиге не будет задан порт.

2022-12-02 06:55 UTC, Licheropew commented on cmd/main.go
> +	if err := s.Serve(c); err != nil {
Переименовал переменные.

2022-12-02 06:56 UTC, Licheropew commented on cmd/main.go
> +	if err := godotenv.Load(); err != nil {
Перенес. Также оставил только функцию main.

2022-12-02 06:59 UTC, Licheropew commented on internal/repositories/courses/user_courses.go
> +package courses
Сделал отдельные репозитории. Также отдельно как репо вынес базу данных (там где методы Init, Close). Может это не совсем корректно, но показалось логичным по структуре.
Добавил конструктор, который создает соответствующий интерфейсу объект. По-возможности посмотри, пожалуйста, все ли корректно здесь.

2022-12-02 07:05 UTC, Licheropew commented on .gitignore
> +*.env
Добавил.

2022-12-02 12:01 UTC, Licheropew commented on api/proto/courses.proto
> +    string status = 6;
Добавил ENUM. Добавил в модель соответствующие константы. Добавил функцию, которая при инициализации базы данных будет проверять и при необходимости создавать ENUM тип status.
Добавил дополнительную функцию, которая помогает выбирать статус (для экономии места).

2022-12-02 12:01 UTC, Licheropew commented on api/proto/courses.proto
> +    string status = 3;
Добавил.

2022-12-02 13:41 UTC, RealJimy requested changes

2022-12-02 13:41 UTC, RealJimy commented on internal/api/courses.go
> +			return nil, status.Error(codes.Aborted, utils.ErrCourseWasDeleted.Error())
Я не уверен, что в данном случае нужно возвращать ошибку. Ведь по сути ничего не сломалось, данные не потерялись, элемент остался удаленным.
По результату это неотличимо от нормального удаления.
Максимум, можно залогировать чтобы выяснить, кто пытается удалять уже удаленные элементы и пофиксить на той стороне.

2022-12-02 13:41 UTC, RealJimy commented on internal/api/courses.go
> +	result.Total = int32(len(courses))
Total я имел ввиду не количество найденных элементов, а общее количество без учета limit и offset.

2022-12-02 13:41 UTC, RealJimy commented on internal/api/courses.go
> +		if uc.PercentFinished != 0 {
В чем особенность кейса когда % == 0? Почему его нужно игнорить?

2022-12-02 13:56 UTC, Licheropew commented on internal/api/courses.go
> +		if uc.PercentFinished != 0 {
Нет особенностей, добавлял для одной из проверок. Вернул как было изначально - заполняю сразу в структуре без проверок.

2022-12-02 14:54 UTC, Licheropew commented on internal/api/courses.go
> +	result.Total = int32(len(courses))
Понял, переделал.
Изначально рассуждал о том, что можно кинуть запрос без limit и offset, получить общее количество, а дальше уже относительно этого значения работать.
Сейчас будет возвращаться количество всех записей в таблице, правда через второй запрос к базе, но думаю что ничего критичного нет. Проверку на ошибку оставил. В запросе limit и offset ставлю нулевыми.

2022-12-02 15:07 UTC, Licheropew commented on internal/api/courses.go
> +			return nil, status.Error(codes.Aborted, utils.ErrCourseWasDeleted.Error())
В целом согласен, ничего не ломается, значит ошибку возвращать не нужно.
Я саму ошибку оставлю и проверку на тип этой ошибки, думаю лишним не будет, чтобы отлавливать такие случаи. Вместо return пока сделаю log.Println.

2022-12-03 11:27 UTC, RealJimy requested changes

2022-12-03 11:27 UTC, RealJimy commented on internal/api/courses.go
> +			return nil, status.Error(codes.Internal, err.Error())
Текст ошибки из недр бэкегда ничем не поможет клиенту если он не злойхакер.

2022-12-05 07:10 UTC, Licheropew commented on cmd/main.go
> +	if err := myDb.Init(dbUrl); err != nil {
Не знаю правильно ли будет, но можем сделать dbUrl (или назвать dataSourceName, или dsn) и сделать её пустым интерфейсом. Соответственно, функция Init также будет принимать интерфейс, а уже в функции просто добавить проверку на тип интерфейса для каждой подключаемой базы данных.

2022-12-05 07:16 UTC, Licheropew commented on cmd/main.go
> +	conf := config.New()
да, я слышал о таком.
я здесь скорее сделал для себя логическое разделение (на случай разбиения по функциям отдельным: инициализация бд и создание grpc).
вообще не люблю комментарии оставлять, если в них нет крайней необходимости.

2022-12-05 07:52 UTC, Licheropew commented on cmd/main.go
> +		log.Printf("Database connection error: %s", err.Error())
Поменял на log.Fatalf

2022-12-05 07:57 UTC, Licheropew commented on cmd/main.go
> +	listener, err := net.Listen("tcp", fmt.Sprintf(":%s", port))
Сделал нечто подобное. Добавил функцию, которая возвращает дефолтное значение, если ENV параметр не задан.
https://habr.com/ru/post/446468/ - достаточно интересно и просто расписано
Также добавил такую же функцию для других параметров, там дефолтно пустые значения возвращаю, потом можно договориться о значениях по-умолчанию.

2022-12-05 08:04 UTC, Licheropew commented on cmd/main.go
> +	if conf.Port != "" {
Пока сделал для дефолтного значения через доп. функцию. Viper посмотрю. Если что, переделаю потом через него.

2022-12-05 15:45 UTC, Licheropew commented on internal/api/courses.go
> +		return uc, status.Error(codes.InvalidArgument, utils.ErrInvalidFormat.Error())
Я добавил возврат пустой структуры, так как хоть что-то возвращать нужно и логически правильнее.
Но и возврат значения, которое не используется, по идее не мешает нигде :)

2022-12-05 19:42 UTC, RealJimy commented on cmd/main.go
> +	if err := myDb.Init(dbUrl); err != nil {
Пустой интерфейс не очень.
На самом деле, весь код начиная от `switch conf.DBType {` и до этой строки это фабрика - его наверное можно вынести в отдельную функцию, которая может принимать на вход конфиг и возвращать myDb с уже выполненным подключением.
Давай оставим пока этот момент на потом, может еще что-то поменяется до конца ревью

2022-12-05 19:59 UTC, RealJimy commented on internal/api/courses.go
> +		return uc, status.Error(codes.InvalidArgument, utils.ErrInvalidFormat.Error())
1) "Хоть что-то возвращать нужно" - ну да, nil
2) Это мешает понимать код. Если возвращается какое-то значение, то ожидаешь, что это сделано с какой-то целью. Потом дальше по коду оно отбрасывается и возникают сомнения, что я упустил что-то из виду - начинаешь пересматривать код с мыслью "ну для чего-то же оно передается". Тратится дополнительное время на "расследование".

2022-12-06 08:33 UTC, Licheropew commented on internal/api/courses.go
> +		return nil, status.Error(codes.InvalidArgument, utils.ErrInvalidFormat.Error())
Добавил ошибку ErrInvalidUUIDFormat, возвращаю её на проверках UUID.
Тут добавил возврат кода OutOfRange, добавил также ошибку с текстом out of range.

2022-12-06 08:33 UTC, Licheropew commented on internal/api/courses.go
> +	if err != nil {
Везде где можно привёл к такому виду. Чуть меньше кода всегда лучше :)

2022-12-06 08:33 UTC, Licheropew commented on internal/api/courses.go
> +	if err := cs.DB.Update(request.GetId(), request.GetTitle(), request.GetDescription()); err != nil {
Fixed.

2022-12-06 08:36 UTC, Licheropew commented on internal/utils/utils.go
> +
Я пока просто перенес в пакет internal (и в соответствующую папку). Подсмотрел в одной из статей, что так периодически делают, если есть какие-то кастомные ошибки. Но возможно есть ещё какое-то решение.
Называть пакет errors не хочется, так как переплетается с таким же встроенным пакетом.

2022-12-06 08:37 UTC, Licheropew commented on internal/api/courses.go
> +			return uc, status.Error(codes.Internal, err.Error())
Я пока буду возвращать пустую структуру (в целом так можно делать, как вариант), так как nil здесь вернуть не получится - структура не может быть nil.
Возможно подумаю над оптимизацией, как переделать функцию так, чтобы она возвращала не структуру, а работала со ссылкой и просто возвращала ошибку.

2022-12-07 17:02 UTC, RealJimy requested changes

2022-12-08 07:23 UTC, Licheropew commented on internal/interfaces/courses.go
> +	UserCourseStoreManager
Дело в названии или в логике? К курсам, как к модели да, не имеет.
А к курсам, как к полноценному сервису, который и разрабатываем, с моей точки зрения, прямое.
Опять-таки, объединение интерфейсов показывает, что сервис умеет делать и с кем общаться.

2022-12-12 14:59 UTC, Licheropew commented on internal/api/courses.go
> +			return nil, status.Error(codes.Internal, err.Error())
Внес изменения во всех фрагментах, где это встречалось. Добавил также везде логирование, где есть внутренняя ошибка. Добавил статическую внутреннюю ошибку.

2022-12-13 22:11 UTC, merged